{% set name = "eo-learn-features" %}
{% set version = "0.7.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9b6e6d6cfe4f08c1ce7d608c7393bd82a195093ecf55cd1357a86ecf408ad907

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - eo-learn-core
    - numba >=0.43.1
    - numpy
    - python
    - python-dateutil
    - scikit-image
    - scikit-learn
    - scipy

test:
  imports:
    - eolearn
    - eolearn.features

about:
  home: https://github.com/sentinel-hub/eo-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of feature manipulation utilities and EOTasks
  doc_url: https://eo-learn.readthedocs.io/en/latest/eolearn.features.html
  dev_url: https://github.com/sentinel-hub/eo-learn

extra:
  recipe-maintainers:
    - mwilson8
    - dcunn
    - oblute
    - rluria14
    - benhuff
